
namespace PK
{
    enum DB_Table
    {
        DICTIONARIES,
        DICTIONARIES_ITEMS,
        USERS,
        TARGET_ORGANIZATIONS,
        DICTIONARY_10_ITEMS,
        FACULTIES,
        PROFILES,
        _FACULTIES_HAS_DICTIONARY_10_ITEMS,
        CAMPAIGNS,
        CAMPAIGNS_DIRECTIONS_DATA,
        CAMPAIGNS_FACULTIES_DATA,
        CAMPAIGNS_PROFILES_DATA,
        _CAMPAIGNS_HAS_DICTIONARY_10_ITEMS,
        _CAMPAIGNS_HAS_DICTIONARIES_ITEMS,
        TARGET_ORGANISATIONS_ADM_VOLUMES,
        DIR_ENTRANCE_TESTS
    }
}
